openapi: 3.0.1
info:
  title: '@jupiterone/dynamodb-dao'
  description: DynamoDB Data Access Object (DAO) helper library
  x-cortex-git:
    github:
      repository: JupiterOne/dynamodb-dao
  x-cortex-owners:
    - type: group
      name: JupiterOne/mercury
  x-cortex-tag: '@jupiterone/dynamodb-dao'
  x-cortex-service-groups:
    - tier-4
