services:
  dynamodb:
    image: 'amazon/dynamodb-local:latest'
    ports:
      - 8000:8000
  test:
    image: node:24-alpine
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    volumes:
      - ./:/opt/work:delegated
    working_dir: /opt/work
    command: sh -c "npm test -- --ci"
