version: '3'

services:
  dynamodb:
    image: 'public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:1.19.0'
    ports:
      - 8000:8000
  test:
    image: public.ecr.aws/docker/library/node:18-alpine3.16
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    volumes:
      - ./:/opt/work:delegated
    working_dir: /opt/work
    command: sh -c "yarn jest --ci"
