version: '3'

services:
  dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - 8000:8000
  test:
    image: node:12.10-alpine
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    volumes:
      - ./:/opt/work:delegated
    working_dir: /opt/work
    command: sh -c "yarn jest --ci"
